server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: eHmTzE45Of
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope: openid, profile, email

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

logging:
  level:
    org.springframework.security: DEBUG

google:
  client:
    id: ${GOOGLE_OAUTH_CLIENT_ID}
    secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
  redirect:
    uri: http://localhost:4200/auth/callback
  url:
    tokenUrl: https://oauth2.googleapis.com/token
    userInfoUrl: https://www.googleapis.com/oauth2/v3/userinfo

